### PR TITLE
➕ Add Storybook

### PR DESCRIPTION
**Pull request by cboenke**
https://storybook.js.org/docs/react/get-started/install

- Install Storybook using: `npx sb init`
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in `.storybook/main.js`
- Load example component in `pages/index.tsx`
- Ignore `/storybook-static`
- Add `.eslintignore`

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by mrana17 — APPROVED** [review]
gj 👍

**Review by m-wiemers — APPROVED** [review]
Every day so hardworking 🔨🛠

**Review by sweisz — APPROVED** [review]

**Pull request merged**
